# Generated by Django 3.2.25 on 2025-02-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('addedDate', models.DateField(max_length=15)),
            ],
            options={
                'db_table': 'sos_favoritelist',
            },
        ),
    ]
