# Generated by Django 3.2.25 on 2025-02-13 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_favoritelist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteList',
            new_name='Favorite',
        ),
        migrations.AlterModelTable(
            name='favorite',
            table='sos_favorite',
        ),
    ]
