# Generated by Django 3.2.25 on 2025-02-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20250213_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='addedDate',
            field=models.DateField(default='', max_length=15),
        ),
    ]
