# Generated by Django 3.2.25 on 2025-02-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_favorite_addeddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='addedDate',
            field=models.DateField(),
        ),
    ]
