# Generated by Django 3.2.25 on 2025-02-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_favorite_addeddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=30)),
                ('joiningDate', models.DateField(max_length=15)),
                ('division', models.CharField(max_length=30)),
                ('previousEmployer', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_Staff',
            },
        ),
    ]
