# Generated by Django 3.2.25 on 2025-02-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('openingDate', models.DateField(max_length=15)),
                ('requiredExperience', models.CharField(max_length=30)),
                ('condition', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sos_Position',
            },
        ),
    ]
