# Generated by Django 3.2.25 on 2025-03-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('overview', models.CharField(max_length=25)),
                ('cost', models.CharField(max_length=30)),
                ('purchaseDate', models.DateField(max_length=15)),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sos_Item',
            },
        ),
    ]
