# Generated by Django 4.2.19 on 2025-03-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=50)),
                ('dataType', models.CharField(max_length=30)),
                ('isActive', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'sos_Attribute',
            },
        ),
    ]
