# Generated by Django 4.2.19 on 2025-04-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('userName', models.EmailField(max_length=25)),
                ('password', models.CharField(max_length=15)),
                ('birthDate', models.DateField(max_length=20)),
                ('contactNumber', models.IntegerField(max_length=20)),
            ],
            options={
                'db_table': 'sos_Employee',
            },
        ),
    ]
