# Generated by Django 3.2 on 2025-05-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contactNumber',
            field=models.CharField(max_length=15),
        ),
    ]
