# Generated by Django 3.2 on 2025-06-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_employee_contactnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('contactNUmber', models.CharField(max_length=15)),
                ('importance', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_Customer',
            },
        ),
    ]
